### ISSUE TITLE
Object appearing very strange with rapid movements

### ISSUE THREAD

**Issue by steechyyy** [tbvns/GD3D#1] opened 2024-03-31 02:25 UTC
Yeah, the program seems to struggle with importing the animation i gave to it.. Instead of moving smoothly, like in the first video, it zaps around from top to bottom, even after adjusting some of the options available inside of the program (like skip frames). 

### this is how it's supposed to look:
https://github.com/tbvns/GD3D/assets/91980836/b2428d50-a64d-46a3-a636-735eff85274d

### this is how it ends up when converted to gd level:
https://github.com/tbvns/GD3D/assets/91980836/3c9b33d2-4e5f-472d-9ceb-4628c60b85db

### the triggers the program has created:
![Screenshot 2024-03-31 042420](https://github.com/tbvns/GD3D/assets/91980836/623e5608-fc60-4f61-85a0-26ea12fe5998)

### this is the blender file for the animation:
https://drive.google.com/file/d/1vtB18c2U1VnyCaZ5Y4TIqSi8YrnbtVOJ/view?usp=sharing
_(had to upload on drive since it didn't let me upload the .blend)_

maybe i did something wrong, maybe I'm overseeing something, maybe its an error in the code, probably [the gradient triggers arent placed properly.](https://github.com/tbvns/GD3D/wiki#why-does-my-animation-look-strange-) I'm not too sure, i'm not really a programmer, but after looking through the FAQ i couldnt find much more information that could help me. to my knowledge everything is also installed correctly.

I have to say though, that this program even kinda does something in the first place is, i think, really insane. You have a banger thing going so far and i cant wait to see it improved and working just flawlessly!!

**Comment by tbvns** [comment] 2024-03-31 10:49
That's really strange, I'll take a look at that when I get home. Try to set the skip frame settings to 0,
I think gradient triggers aren't the issue here, it may be caused by the code that places/reads the position of the keyframes.

**Comment by tbvns** [comment] 2024-03-31 11:05
Can you send me the settings you used ? It might help to resolve this.

**Comment by tbvns** [comment] 2024-03-31 16:22
I tried to replicate this issue, but here is the result:
![video](https://github.com/tbvns/GD3D/assets/69420062/a6050b76-1227-4e26-919d-559f3d5f3519)
Here is my config:
![image](https://github.com/tbvns/GD3D/assets/69420062/0410ca14-e30f-4860-b06a-ff391813b4c7)
There is still a bug with one gradient appearing in front of another one, ill fix that in the next update.

**Comment by steechyyy** [comment] 2024-04-01 00:00
after i imported it with your settings, still the same things happened. with skip frame set to 0, it also still happens

https://github.com/tbvns/GD3D/assets/91980836/183f89d6-d667-44bc-997d-7c5b23e2c9af

**Comment by tbvns** [comment] 2024-04-01 00:43
That might be an issue related to Windows or something, it's 3am right now so ill fix this in the morning, ill try to replicate this issue in a VM since I can't replicate this issue on linux. I have a potential explanation. The way the program locate frames is by locating every file in the selected folder that end with .obj or .mtl. If the file are not given in the right order, it causes strange issue like that. That is just a theory, but it is my best one yet. Windows and linux don't have the same way of managing file, that might explain why you get the issue and I don't. You can try to rename the file (in blender make the name of the exported file 0.obj or something like that) it might help. The next update will add a proper fix to this.

**Comment by steechyyy** [comment] 2024-04-01 14:57
after renaming the files still the exact same thing happens. Well, it's okay, ill keep an eye out for the next update!

**Comment by tbvns** [comment] 2024-04-04 21:06
I'm planning to release the update in the week, I already have a potential "fix build" of the app, but I don't have Geometry Dash on my vm, so I can't really test it right now, ill test it tomorrow.

**Comment by tbvns** [comment] 2024-04-06 20:01
Should be fixed in https://github.com/tbvns/GD3D/commit/86ff60991770f9f4511f532b2c5e83b30df313ae. If the issue persiste, reopen this issue.

**Comment by tbvns** [comment] 2024-04-06 20:41
The latest release includes this commit, take a look at it. And if you like the project, please star it, it will help with the GitHub algorithm. It's like likes on YouTube.

**Comment by steechyyy** [comment] 2024-04-06 21:59
Hi, i rlly appreciate the time ur taking for this project!!
unfortunately the issue still persists even after the newest release. It changed a bit from what it looked like beforehand, so something definitely happened, but it still isnt the exact animation

https://github.com/tbvns/GD3D/assets/91980836/ed2eeaeb-04d6-4129-a64a-4419664eda8c

What i also noticed while recording was that it sometimes doesnt spit out the exact same results, even when the settings are the same, that **might** be a whole nother issue

**Try 1**

![Screenshot 2024-04-06 235003](https://github.com/tbvns/GD3D/assets/91980836/6ee074d7-5cca-426d-89d9-4d5f601d516e)

**Try 2**

![Screenshot 2024-04-06 235110](https://github.com/tbvns/GD3D/assets/91980836/0605dfc7-b59e-497b-a2b0-8ef3496a502b)

**Try 3 (rlly short this time)**

![Screenshot 2024-04-06 235557](https://github.com/tbvns/GD3D/assets/91980836/51f35a66-6208-4467-8080-7f94ea1e54f4)

I used the default settings (except skip frames) for every one of these

 I starred the project btw, i never knew you could do that lol, i dont use github often. As soon this starts working ill lowkey share this around with my friends, this would be so well usable and easy to understand if it werent for the issues

**Comment by tbvns** [comment] 2024-04-07 15:08
My fixe was working, but the windows detection code used "window" instead of "Windows", the code you were running was supposed to be the Linux one. Fixed in https://github.com/tbvns/GD3D/commit/5ef2336bec499109f83cd042e2018d7983bc7ea5.

**Closed as completed by tbvns** 2024-04-07 15:08 UTC
Labels: bug

**Comment by tbvns** [comment] 2024-04-08 16:04
Is the patch working for you? It's in the GD3D  Beta 0.0.6 update.

**Comment by steechyyy** [comment] 2024-04-14 08:33
Hello, sorry for not having responded earlier, i forgot =[
Yup, the patch works just as intended now, ty very much for taking your time to fix! Im very excited for future versions of this program !!
